[package]
name = "fuzz"
version.workspace = true
edition.workspace = true

[package.metadata]
cargo-fuzz = true

[[bin]]
name = "parse_lower"
path = "fuzz_targets/parse_lower.rs"

[dependencies]
libfuzzer-sys.workspace = true
elysium = { path = "../elysium" }
